name: Build and Publish for Windows

on:
  push:
    tags:
      - "v*" # Trigger only on version tags like v1.0.0

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build and package with electron-builder
        run: npm run build

      - name: Set version variable
        id: vars
        shell: pwsh
        run: |
          $version = "${{ github.ref_name }}".TrimStart("v")
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Fetch previous version
        id: previous_version
        shell: bash
        run: |
          latest_tag=$(gh release view --json tagName --jq .tagName)
          echo "previous_version=${latest_tag#v}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download previous blockmap (optional)
        run: |
          mkdir -p release/${{ steps.vars.outputs.version }}
          curl -fL "https://github.com/jakeyizle/melee-dex/releases/download/v${{ env.previous_version }}/melee-dex_${{ env.previous_version }}.exe.blockmap" \
            -o "release/${{ steps.vars.outputs.version }}/melee-dex_${{ env.previous_version }}.exe.blockmap" || echo "Previous blockmap not found, continuing without it."

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/${{ steps.vars.outputs.version }}/melee-dex_${{ steps.vars.outputs.version }}.exe
            release/${{ steps.vars.outputs.version }}/melee-dex_${{ steps.vars.outputs.version }}.exe.blockmap
            release/${{ steps.vars.outputs.version }}/latest.yml
            release/${{ steps.vars.outputs.version }}/melee-dex_${{ env.previous_version }}.exe.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
